### ISSUE TITLE
ワンポイントアドバイス

### ISSUE THREAD

**Issue by t-sakurai816** [natsuki-1746/Visual_Web#1]
[index.html](https://github.com/natsuki-1746/Visual_Web/blob/master/index.html)の`<br>`は使わないほうが良いよ  
`<br>`を使うと、デバイスによってスタイルが崩れてしまうので、`<div>`とかでくくったほうがよい。  
文字書くなら`<p>`とかね

**Comment by natsuki-1746** [comment]
そうか<p>か、なんだっけとか思いながら<a>でやってた、、、
ありがとう！直します!!

**Comment by natsuki-1746** [comment]
なんか消えちゃった＜ｐ＞と＜a＞って書きました()
表示されるかな、、？

**Comment by t-sakurai816** [comment]
pushされていないみたいだから、俺からは確認できない...

`<a>`を使うのはリンクを表すときなので、単純に文字を書きたいときは`<p>`囲みがいいです！

**Comment by t-sakurai816** [comment]
いい感じですね^^
イシューを閉じます
